### PR TITLE
Some very opinionated changes.

### PR DESCRIPTION
**Pull request by SimonGreenhill**
I'd be tempted to remove all the NewLexeme etc stuff as being too much boilerplate. One example? feel free to disagree!

### CODE REVIEW

**Comment by LinguList** [comment]
I'd say, similar to the sphinx template, it would be good to expose all complexity, and uncomment it. If this is then too much, I'd opt for two templates, one simple, and one more complex, as I will need the more complex cases in almost all data from SEA languages, where, e.g., `Lexeme` needs to be rewritten, as we often have Chinese characters.

**Review by LinguList — APPROVED** [review]
I basically agree, I guess, the major point is also, that we have the FormSpec always in there, to avoid fiddling with custom-code with words (which may still be needed, but should be the exception). We might find a compromise with respect to complexity by adding a second template that shows also how to handle cognates and lexemes. I mean, this is a template folder, so adding another `lexibank_template_with_cognates.py` won't really hurt.

**Comment by SimonGreenhill** [comment]
Yes! let's  have a simple template and a complex template. I was worried if we had all the complexity in it, then this would lead to cutting-and-pasting without thinking and lots of wasted code.

**Comment by LinguList** [comment]
I'd like to say: I feel very comfortable with @xrotwang's suggestions on the new pylexibank/cldfbench, and it did not really take me long to get into the code. 

I was just thinking: we could use this repo as a collection of templates for different purposes? I mean: I always open bodtkhobwa if I am looking for partial cognates, and I search often a lot in the existing files to find the one or the other solution. 

So what about: adding a README.md here and summarizing what each template can do? Starting with the simple one, following @SimonGreenhill, and then adding specific-purpose-templates for more complex usecases?

**Comment by LinguList** [comment]
> Yes! let's have a simple template and a complex template. I was worried if we had all the complexity in it, then this would lead to cutting-and-pasting without thinking and lots of wasted code.

As long as I'm not fluent (and with the many packages, I have problems catching up), I just need some place where I can look things up (as mentioned before). I also reckon this will help in the future. Newbies can start with the simplest template, and if one wants to add partial cognates with alignments, there's another one. Even a collection in form of code-snippets here would help, as we are getting to a point where looking in the source code gets tedious.

**Comment by LinguList** [comment]
I merge this now. I suppose we further modify the structure of this folder, and allow for individual templates to be submitted, which are briefly explained in a readme, so we know what purpose they serve.

**Pull request merged**
